#!/bin/bash 
###################################################################
#Script Name   : dependencies
#Description   : Export docker images tags for razvid-ner project
#Args          :
#Author        : Tadej Justin 
#Email         : tadej.justin@medius.si
###################################################################


                                             
# Releases: https://hub.docker.com/r/library/redis/tags/
export REDIS_TAG="5-alpine"

# Releases: https://hub.docker.com/r/library/mongo/tags/
export MONGO_TAG="4.2-bionic"

export SLOTEX_NLP_CORE_TAG="1.0.0"
export SLOTEX_NLP_WEB_TAG="1.0.0"

